# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 160)
        MainWindow.setMinimumSize(QtCore.QSize(420, 160))
        MainWindow.setMaximumSize(QtCore.QSize(420, 160))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 10, 141, 20))
        self.label.setObjectName("label")
        self.file_url = QtWidgets.QLineEdit(self.centralwidget)
        self.file_url.setGeometry(QtCore.QRect(10, 50, 341, 20))
        self.file_url.setObjectName("file_url")
        self.push_go = QtWidgets.QPushButton(self.centralwidget)
        self.push_go.setGeometry(QtCore.QRect(180, 90, 81, 23))
        self.push_go.setObjectName("push_go")
        self.file_change = QtWidgets.QPushButton(self.centralwidget)
        self.file_change.setGeometry(QtCore.QRect(360, 50, 41, 23))
        self.file_change.setObjectName("file_change")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Выберите файл с ссылками"))
        self.push_go.setText(_translate("MainWindow", "Go"))
        self.file_change.setText(_translate("MainWindow", "file"))
